seajs.config({
      alias: {
          'ui': 'ui/ui',
          'iscroll': 'libs/iscroll',
          'swipeout': 'libs/swipeout',
          'accordion' : 'ui/widgets/accordion',
          'accordionList' : 'ui/widgets/accordionList',
          'button' : 'ui/widgets/button',
          'checkbox' : 'ui/widgets/checkbox',
          'dialog' : 'ui/widgets/dialog',
          'radio' : 'ui/widgets/checkbox',
          'select' : 'ui/widgets/select',
          'input' : 'ui/widgets/input',
          'switch':'ui/widgets/switch',
          'slider':'ui/widgets/slider/slider',
          'sGuide':'ui/widgets/slider/guide',
          'sTouch':'ui/widgets/slider/touch',
          'sGestures':'ui/widgets/slider/gestures',
          'sMultiview':'ui/widgets/slider/multiview',
          'swipelist' : 'ui/widgets/swipelist',
          'tab' : 'ui/widgets/tabs/tabs',
          'navigator' : 'ui/widgets/navigator',
          'swipePage' : 'ui/widgets/swipePage',
          'treeview' : 'ui/widgets/treeview',
          'refresh' : 'ui/widgets/refresh',
          'fullpage' : 'ui/widgets/fullpage',
          'searchbar' : 'ui/widgets/searchbar',
          'photoBrowser' : 'ui/widgets/photoBrowser',
          'lazyLoadImage' : 'ui/widgets/lazyLoadImage',
          'scroll' : 'ui/widgets/iscroll'
      },
      preload: ['ui','button','checkbox','select','input']
  });