var data = [{
    cont: "accordion",
    name: "accordion",
    tar: "accordion.html"
}, {
    cont: "按钮",
    name: "control",
    tar: "button.html"
}, {
    cont: '列表',
    contents: [{
        cont: 'deflistview',
        tar: "listview/deflistview.html"
    }, {
        cont: 'medialistview',
        tar: "listview/medialistview.html"
    }, {
        cont: 'customlistview',
        tar: "listview/customlistview.html"
    }, {
        cont: 'swipelistview',
        tar: "listview/swipelistview.html"
    }]
}, {
    cont: '导航',
    name: "listview",
    tar: "header.html"
}, {
    cont: '弹出框',
    name: "Dialog",
    tar: "dialog.html"
}, {
    cont: 'card',
    name: "card",
    tar: "cards.html"
}, {
    cont: '滚屏',
    name: "fullpage",
    tar: "fullpage.html"
}, {
    cont: '搜索框',
    name: "searchbar",
    tar: "searchbar.html"
}, {
    cont: '图片浏览器',
    name: "photoBrowser",
    tar: "photoBrowser.html"
}, {
    cont: '图片懒加载',
    name: "lazyLoadImage",
    tar: "lazyLoadImage.html"
}, {
    cont: '文本框',
    name: "listview",
    tar: "input.html"
}, {
    cont: '轮播图',
    name: "listview",
    tar: "slider.html"
}, {
    cont: '进度条',
    name: "progressBar",
    tar: "progressBar/progressbar.html"
}, {
    cont: 'request',
    name: "request",
    tar: "request/request.html"
}, {
    cont: '开关',
    name: "listview",
    tar: "switche.html"
}, {
    cont: "Native",
    contents: [{
        cont: 'accelerometer',
        tar: "accelerometer.html"
    }, {
        cont: 'alert',
        tar: "alert.html"
    }, {
        cont: 'audio',
        tar: "audio.html"
    }, {
        cont: 'barcode',
        tar: "barcode.html"
    }, {
        cont: 'camera',
        tar: "camera.html"
    }, {
        cont: 'contacts',
        tar: "contacts.html"
    }, {
        cont: 'databace',
        tar: "databace.html"
    }, {
        cont: 'device',
        tar: "device.html"
    }, {
        cont: 'download',
        tar: "download.html"
    }, {
        cont: 'gallery',
        tar: "gallery.html"
    }, {
        cont: 'geolocation',
        tar: "geolocation.html"
    }, {
        cont: 'storage',
        tar: "storage.html"
    }, {
        cont: 'testLog',
        tar: "testLog.html"
    }, {
        cont: 'windowTest',
        tar: "windowTest.html"
    }, {
        cont: 'zip',
        tar: "zip.html"
    }]
}, {
    cont: 'Tab bar',
    name: "listview",
    tar: "tabs.html"
}, {
    cont: 'Nav bar',
    name: "navigator",
    tar: "navigator.html"
}, {
    cont: 'swipePage',
    name: "swipePage",
    tar: "swipePage.html"
}, {
    cont: 'refresh',
    name: "refresh",
    tar: "refresh.html"
}, {
    cont: 'news',
    name: "news",
    tar: "news.html"
}, {
    cont: '树形列表',
    name: "listview",
    tar: "treeview.html"
}];